server:
  port: 8080

spring:
  application:
    name: mall-admin
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: username
    password: password
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      web-stat-filter:
        exclusions: '*.js,*.gif,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        login-username: username
        login-password: password
  redis:
    host: localhost
    database: 0
    port: 6379
    password: password
    connect-timeout: 3000ms
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

mybatis:
  mapper-locations: 
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always